markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Mike Jahn
url: http://mikejahn.com
description: Software Engineer
twitter: mikejahn
github: mikejahn
gravatar_url: http://www.gravatar.com/avatar/78584e4bac5acdddaa3f4d1e2763f9ba
